const test = require('tape')

const data = require('..')

test('shape', t => {
  t.equal(data.api_mst_ship.find(e => e.api_name === '睦月').api_id, 1)
  t.equal(data.api.api_mst_ship.find(e => e.api_name === '睦月').api_id, 1)

  t.equal(data.api.getShip({ name: '睦月' }).api_id, 1)
  t.equal(data.api.getShipType({ name: '海防艦' }).api_id, 1)
  t.equal(data.api.getEquipment({ name: '12cm単装砲' }).api_id, 1)
  t.equal(data.api.getEquipmentType({ name: '小口径主砲' }).api_id, 1)
  t.equal(data.api.getItem({ name: '高速修復材' }).api_id, 1)

  t.equal(data.map.edges[445][1][1], 'A')
  t.equal(data.map.diffs[1], 'Casual')
  t.equal(data.map.formations[1], 'Line Ahead')
  t.equal(data.map.regularMaps[0], 11)
  t.equal(data.map.battleRanks[0], 'S')
  t.equal(data.map.getNodeType(5, 5, 5), 'Boss')
  t.equal(data.map.getDiff(1), 'Casual')
  t.equal(data.map.getDiffId('Casual'), 1)
  t.equal(data.map.getFormation(1), 'Line Ahead')
  t.equal(data.map.getFormationId('Line Ahead'), 1)
  t.equal(data.map.getNodeLabel(445, 1), 'A')
  t.equal(data.map.getNodeLabels(445)[0], 'A')

  t.equal(data.tl('睦月'), 'Mutsuki')
  t.equal(data.tl.ship['睦月'], 'Mutsuki')
  t.equal(data.tl.tlShip('睦月'), 'Mutsuki')
  t.equal(data.tl.tlShipFromId(1), 'Mutsuki')
  t.equal(data.tlShip('睦月'), 'Mutsuki')
  t.equal(data.tlShipFromId(1), 'Mutsuki')

  t.equal(data.tl('12cm単装砲'), '12cm Single Gun Mount')
  t.equal(data.tl.equipment['12cm単装砲'], '12cm Single Gun Mount')
  t.equal(data.tl.tlEquipment('12cm単装砲'), '12cm Single Gun Mount')
  t.equal(data.tl.tlEquipmentFromId(1), '12cm Single Gun Mount')
  t.equal(data.tlEquipment('12cm単装砲'), '12cm Single Gun Mount')
  t.equal(data.tlEquipmentFromId(1), '12cm Single Gun Mount')

  t.equal(data.tl('駆逐イ級'), 'Destroyer I-Class')
  t.equal(data.tl.enemy['駆逐イ級'], 'Destroyer I-Class')
  t.equal(data.tl.tlEnemy('駆逐イ級'), 'Destroyer I-Class')
  t.equal(data.tl.tlEnemyFromId(1501), 'Destroyer I-Class')
  t.equal(data.tlEnemy('駆逐イ級'), 'Destroyer I-Class')
  t.equal(data.tlEnemyFromId(1501), 'Destroyer I-Class')

  t.equal(data.tl('北方棲妹-壊_1870'), 'Northern Little Sister - Damaged III')
  t.equal(data.tl.enemy['北方棲妹-壊_1870'], 'Northern Little Sister - Damaged III')
  t.equal(data.tl.tlEnemy('北方棲妹-壊_1870'), 'Northern Little Sister - Damaged III')
  t.equal(data.tl.tlEnemyFromId(1870), 'Northern Little Sister - Damaged III')
  t.equal(data.tlEnemy('北方棲妹-壊_1870'), 'Northern Little Sister - Damaged III')
  t.equal(data.tlEnemyFromId(1870), 'Northern Little Sister - Damaged III')

  t.equal(data.tl('北方棲妹-壊'), 'Northern Little Sister - Damaged')
  t.equal(data.tl.enemy['北方棲妹-壊'], 'Northern Little Sister - Damaged')
  t.equal(data.tl.tlEnemy('北方棲妹-壊'), 'Northern Little Sister - Damaged')
  t.equal(data.tl.tlEnemyFromId(1868), 'Northern Little Sister - Damaged')
  t.equal(data.tlEnemy('北方棲妹-壊'), 'Northern Little Sister - Damaged')
  t.equal(data.tlEnemyFromId(1868), 'Northern Little Sister - Damaged')

  t.equal(data.tl('5inch単装砲'), '5inch Single Gun Mount')
  t.equal(data.tl.enemyEquipment['5inch単装砲'], '5inch Single Gun Mount')
  t.equal(data.tl.tlEnemyEquipment('5inch単装砲'), '5inch Single Gun Mount')
  t.equal(data.tl.tlEnemyEquipmentFromId(501), '5inch Single Gun Mount')
  t.equal(data.tlEnemyEquipment('5inch単装砲'), '5inch Single Gun Mount')
  t.equal(data.tlEnemyEquipmentFromId(501), '5inch Single Gun Mount')

  t.equal(data.tl('海防艦'), 'Coastal Defense Ship')
  t.equal(data.tl.shipType['海防艦'], 'Coastal Defense Ship')
  t.equal(data.tl.tlShipType('海防艦'), 'Coastal Defense Ship')
  t.equal(data.tl.tlShipTypeFromId(1), 'Coastal Defense Ship')
  t.equal(data.tlShipType('海防艦'), 'Coastal Defense Ship')
  t.equal(data.tlShipTypeFromId(1), 'Coastal Defense Ship')

  t.equal(data.tl('小口径主砲'), 'Small Caliber Main Gun')
  t.equal(data.tl.equipmentType['小口径主砲'], 'Small Caliber Main Gun')
  t.equal(data.tl.tlEquipmentType('小口径主砲'), 'Small Caliber Main Gun')
  t.equal(data.tl.tlEquipmentTypeFromId(1), 'Small Caliber Main Gun')
  t.equal(data.tlEquipmentType('小口径主砲'), 'Small Caliber Main Gun')
  t.equal(data.tlEquipmentTypeFromId(1), 'Small Caliber Main Gun')

  t.equal(data.tl('高速修復材'), 'Instant Repair Material')
  t.equal(data.tl.item['高速修復材'], 'Instant Repair Material')
  t.equal(data.tl.tlItem('高速修復材'), 'Instant Repair Material')
  t.equal(data.tl.tlItemFromId(1), 'Instant Repair Material')
  t.equal(data.tlItem('高速修復材'), 'Instant Repair Material')
  t.equal(data.tlItemFromId(1), 'Instant Repair Material')

  t.equal(data.wiki.ship['Mutsuki Kai Ni']._japanese_name, '睦月改二')
  t.equal(data.wiki.ship['Mutsuki Kai Ni']._full_name, 'Mutsuki Kai Ni')
  t.deepEqual(data.wiki.ship['Mutsuki Kai Ni']._implementation_date, [2015, 4, 23])
  t.equal(data.wiki.ship['Mutsuki Kai Ni']._voice_actor, 'Hidaka Rina')

  t.equal(data.wiki.quest.A1.title, 'はじめての「編成」！')

  t.end()
})
