name: Update
on:
  workflow_dispatch:
    inputs:
      db_query:
        description: DB query
        default: default
      db_event_id:
        description: DB event id
        default: default
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn update
        env:
          DB_QUERY: ${{github.event.inputs.db_query}}
          DB_EVENT_ID: ${{github.event.inputs.db_event_id}}
          WIKI_HOST: ${{ secrets.WIKI_HOST }}
          WIKI_PATH: ${{ secrets.WIKI_PATH }}
          WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
          WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
      - run: |
          git config --global user.name "Botkaze"
          git config --global user.email "gkpyon+1@gmail.com"
          TZ=Asia/Tokyo git add .
          TZ=Asia/Tokyo git commit -m "update: $(date +%Y-%m-%d)"
          git push
